# Generated by Django 4.2.17 on 2025-06-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientdoctormapping',
            options={},
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='mapped_date',
            new_name='assigned_at',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='notes',
        ),
    ]
